name: Automated WEB API tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - run_tests

jobs:
    tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python version: "3.10"
        - name: Install Chrome
          run: sudo apt-get install google-chrome-stable
        - name: Install dependensies
          run: pip install -r requirements.txt
        - name: run_tests
          if: "github.event.inputs.deployment_target == 'run_tests'"
          run: pytest -sv